# Generated by Django 3.1.4 on 2021-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neobis_project', '0002_auto_20210122_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(related_name='orders', to='neobis_project.Curt'),
        ),
    ]
